[tool.poetry]
name = "xxxmate_app_backend"
version = "0.1.0"
description = ""
authors = ["xxx <xxx@xxx.com>", "xxx <xxx@xxx.com>"]

[tool.poetry.dependencies]
python = "3.9.6"
Django = "^3.2.8"
djangorestframework = "^3.12.4"
redis = "^3.5.3"
django-cors-headers = "^3.10.0"
gunicorn = "^20.1.0"
django-storages = "^1.12.1"
django-modeltranslation = "^0.17.3"
django-phonenumber-field = "^5.2.0"
phonenumbers = "^8.12.35"
sentry-sdk = "^1.4.3"
django-3-jet = "^1.0.8"
celery = "^5.1.2"
django-stdimage = "^5.3.0"
loguru = "^0.5.3"
django-push-notifications = "^2.0.0"
drf-yasg = "^1.20.0"
django-filter = "^21.1"
django-polymorphic = "^3.1.0"
django-rest-polymorphic = "^0.1.9"
django-nested-admin = "^3.3.3"
pika = "^1.2.0"
requests = "^2.27.1"
psycopg2-binary = "^2.9.3"
opentelemetry-instrumentation-redis = "^0.28b1"
opentelemetry-api = "^1.9.1"
boto3 = "^1.20.49"
opentelemetry-sdk = "^1.9.1"
opentelemetry-exporter-jaeger = "^1.9.1"
opentelemetry-instrumentation-wsgi = "^0.28b1"
opentelemetry-instrumentation-psycopg2 = "^0.28b1"
opentelemetry-instrumentation-django = "^0.28b1"
opentelemetry-instrumentation-requests = "^0.28b1"
opentelemetry-instrumentation-botocore = "^0.28b1"
plantuml = "^0.3.0"

[tool.poetry.dev-dependencies]
black = "19.10b0"
flake8-polyfill = "1.0.2"
isort = "5.6.4"
coverage = "^6.0.2"
pytest-django = "^4.4.0"
pytest = "^6.2.5"
radon = "^5.1.0"
factory-boy = "^3.2.0"
flake8 = "^4.0.1"
pytest-xdist = "^2.5.0"
pytest-cov = "^3.0.0"
freezegun = "^1.1.0"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
