[tool.poetry]
name = "tddfa"
version = "0.1.0"
description = ""
authors = ["xxx xxx <xxx@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.75.0"
uvicorn = "^0.17.6"
asyncpg = "^0.25.0"
tortoise-orm = "0.17.8"
aerich = "^0.6.2"
requests = "2.26.0"
gunicorn = "^20.1.0"
newspaper3k = "0.2.8"

[tool.poetry.dev-dependencies]
pytest-xdist = "^2.5.0"
pytest-cov = "^3.0.0"
black = "19.10b0"
isort = "^5.10.1"
flake8 = "^4.0.1"
pytest = "6.2.5"

[tool.aerich]
tortoise_orm = "app.db.TORTOISE_ORM"
location = "./migrations"
src_folder = "./."

[tool.black]
line-length = 120

[tool.isort]
profile = 'black'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"